### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by sommereder** [leonardohjines/auctionApp#1]
I did check out the source, but it doesn't start. "npm install" works perfectly, but not "npm start".

The following errors appear in the console:
1. node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.
2. public/javascripts/app/app.component.ts(14,23): error TS2304: Cannot find name 'io'.

How do you import Socket.IO to Angular2? There is no such command anywhere, is it?

**Comment by nenjack** [comment]
1. https://github.com/angular/angular/issues/6468
2. declare const io;

**Comment by nenjack** [comment]
And to answer your question it's in index.html script src

**Comment by nenjack** [comment]
After some googling I fixed this. Check especially changes to index.html:
shim after polyfill and name of app.

**Comment by dmitriyHirniy** [comment]
Hi, i have problems with @angular2/router. When i want use provideRouter() method , i use 
import{provideRouter } from '@angular2/router' and start project. 
In console i see Error 404 can not find localhost:3000/@angular2/router.
Can you help me?

**Comment by Master244** [comment]
Your fix doesn't seem to work anymore? I tried running this after adding your changes 

` GET /rxjs/Subject 404 2.528 ms - 1383
[0] GET /rxjs/observable/PromiseObservable 404 2.434 ms - 1383
[0] Error: Not Found
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/app.js:41:13
[0]     at Layer.handle [as handle_request] (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:312:13)
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:280:7
[0]     at Function.process_params (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:330:12)
[0]     at next (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:271:10)
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:618:15
[0]     at next (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:256:14)
[0]     at Function.handle (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:176:3)
[0]     at router (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:46:12)
[0] Error: Not Found
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/app.js:41:13
[0]     at Layer.handle [as handle_request] (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:312:13)
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:280:7
[0]     at Function.process_params (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:330:12)
[0]     at next (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:271:10)
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:618:15
[0]     at next (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:256:14)
[0]     at Function.handle (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:176:3)
[0]     at router (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:46:12)
[0] GET /rxjs/operator/toPromise 404 2.810 ms - 1383
[0] GET /rxjs/Observable 404 2.195 ms - 1383
[0] Error: Not Found
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/app.js:41:13
[0]     at Layer.handle [as handle_request] (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:312:13)
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:280:7
[0]     at Function.process_params (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:330:12)
[0]     at next (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:271:10)
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:618:15
[0]     at next (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:256:14)
[0]     at Function.handle (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:176:3)
[0]     at router (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:46:12)
[0] Error: Not Found
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/app.js:41:13
[0]     at Layer.handle [as handle_request] (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:312:13)
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:280:7
[0]     at Function.process_params (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:330:12)
[0]     at next (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:271:10)
[0]     at /Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:618:15
[0]     at next (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:256:14)
[0]     at Function.handle (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:176:3)
[0]     at router (/Users/mitchelltieleman/Documents/Work/Ali/auctionApp-master/node_modules/express/lib/router/index.js:46:12)

`

Still get the missing promiseObserable from rxjs?

**Comment by Master244** [comment]
I guess this is not working anymore

https://github.com/Reactive-Extensions/RxJS build is failing where running this project after your fixes gives me 

[0] GET /rxjs/Subject 404 2.528 ms - 1383
[0] GET /rxjs/observable/PromiseObservable 404 2.434 ms - 1383
[0] Error: Not Found

**Comment by nenjack** [comment]
https://github.com/Prozi/auctionApp
